### ISSUE TITLE
[Feature Request] Resize from current dimensions

### ISSUE THREAD

**Issue by jordaniusrex** [lucaorio/sketch-resize#5]
This plugin would be really useful if it could use the object's current width or height as a wildcard for math operations.

Let's say I have 3 rectangles with the dimensions:
32x32, 64x32, 128x32.

I want to make them all 32 pixels wider. So in the width field:
Width = '%w+32'
and would get:
64x32, 96x32, 160x32.

Or, I could use the width value in the height field to get proportioned objects:
Height = '%w*9/16'
and would get:
32x18, 64x36, 128x72

That'd be awesome, right?

**Comment by lucaorio** [comment]
Hey, @jordaniusrex ! Thanks for stopping by.

This would be a very cool feature indeed, but unfortunately I don't have a lot of free time to work on this since I've joined Netflix.

I'll keep the issue open as a reminder, or in case anyone wants to give an help :)

**Comment by ajilderda** [comment]
@jordaniusrex My plugin Sketch Resize Commands might help:
https://github.com/ANGIstudio/Sketch-Resize-Commands

I'm currently rewriting it to make it much more powerful:
https://github.com/ajilderda/Sketch-Commander

**Comment by lucaorio** [comment]
@jordaniusrex I just pushed a couple of fixes, and implemented a few new features. Thanks for the patience! 🙏
